services:
  fin_control_db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  fin_control_app:
    image: fin_control
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    entrypoint: ./entrypoint.sh
    depends_on:
      fin_control_db:
        condition: service_healthy

volumes:
  pgdata: