"""Add superuser column to the users table

Revision ID: 4597f7bf2036
Revises: ae6f95e348a3
Create Date: 2026-06-12 17:44:05.135476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4597f7bf2036'
down_revision: Union[str, Sequence[str], None] = 'ae6f95e348a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('superuser', sa.Boolean(), nullable=True))

    op.execute(
        """
        UPDATE users
        SET superuser = false
        """
    )

    op.alter_column(
        "users",
        "superuser",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'superuser')
    # ### end Alembic commands ###
