"""Remove teste field

Revision ID: de01491b5cf8
Revises: 2521c28839af
Create Date: 2026-06-12 16:29:05.286164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de01491b5cf8'
down_revision: Union[str, Sequence[str], None] = '2521c28839af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teste')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teste', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
